name: yob_kbusiness
repository: https://github.com/yob-kbusiness/yob-kbusiness

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "fvm flutter analyze"
    description: Run flutter analyze in all packages

  test:
    run: melos exec -- "fvm flutter test"
    description: Run tests in all packages

  build_runner:
    run: melos exec -- "fvm dart run build_runner build --delete-conflicting-outputs"
    description: Run build_runner in all packages
    packageFilters:
      dependsOn: build_runner

  format:
    run: melos exec -- "fvm dart format ."
    description: Format all packages

  clean:
    run: melos exec -- "fvm flutter clean"
    description: Clean all packages

  # Backend specific
  api:dev:
    run: cd packages/yob_api && dart_frog dev
    description: Run dart_frog dev server

  api:build:
    run: cd packages/yob_api && dart_frog build
    description: Build dart_frog for production

  # App specific
  app:run:web:
    run: cd apps/yob_app && fvm flutter run -d chrome
    description: Run the app on Chrome

  app:run:mobile:
    run: cd apps/yob_app && fvm flutter run
    description: Run the app on a connected device

  # Database
  db:up:
    run: docker-compose up -d postgres
    description: Start PostgreSQL container

  db:down:
    run: docker-compose down
    description: Stop all Docker containers
